---
- name: Including operating system specific tasks (Debian)
  tags: mono
  import_tasks: mono_debian.yml
  when: ansible_os_family == 'Debian'

- name: Including operating system specific tasks (RedHat)
  tags: mono
  import_tasks: mono_redhat.yml
  when: ansible_os_family == 'RedHat'
...
