---
- name: Ensure mono dependencies are present (RedHat)
  tags: mono
  become: true
  yum:
    name: "{{ mono_deps }}"
    state: present
  vars:
    mono_deps:
      - ca-certificates
      - gnupg
      - yum

- name: Fetching mono repository gpg key for local storage (RedHat)
  tags: mono
  become: true
  get_url:
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-xamarin
    owner: root
    group: root
    mode: 0644
    url: http://download.mono-project.com/repo/xamarin.gpg

- name: Ensure the mono repository gpg key is present (RedHat)
  tags: mono
  become: true
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-xamarin
    state: present

- name: Overlay mono repository configuration (RedHat)
  tags: mono
  become: true
  yum_repository:
    baseurl: "{{ 'http://download.mono-project.com/repo/' + mono_repository + '-stable/' }}"
    description: "{{ ['mono', mono_repository, 'stable']|join('-') }}"
    enabled: true
    gpgcheck: true
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-xamarin
    name: "{{ ['mono', mono_repository, 'stable']|join('-') }}"

- name: Ensure the required mono packages are installed (RedHat)
  tags: mono
  become: true
  yum:
    disable_plugin: "{{ mono_disable_plugin|join(',') }}"
    disablerepo: "{{ mono_disablerepo|join(',') }}"
    enable_plugin: "{{ mono_enable_plugin|join(',') }}"
    enablerepo: "{{ mono_enablerepo|join(',') }}"
    name: "{{ mono_packages }}"
    state: present
  when: mono_packages|length > 0
...
